language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby
  - rbx-2.1.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2.1.1
notifications:
  irc: "irc.freenode.org#adhearsion"
