dist: xenial
language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.3
  - jruby-9.1.17.0
  - jruby
  - ruby-head
jdk:
  - openjdk8 # for jruby
matrix:
  allow_failures:
    - rvm: ruby-head
before_install: rvm list
notifications:
  irc: "irc.freenode.org#adhearsion"
